services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appContainer
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:8.0.44
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: central
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_PASSWORD: 1234567
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge